### ISSUE TITLE
Typo: kinf instead of kind

### ISSUE THREAD

**Issue by nuritnt** [peterpeterparker/ionicv4-and-beyond#1]
https://github.com/peterpeterparker/ionicv4-and-beyond/blob/fe03ec5e68fc2d2e5804d919e7ac3030cff6fdba/src/index.html#L109

**Comment by peterpeterparker** [comment]
@nuritnt haha I remembered that I had to fix a "f" typo but didn't remembered which "f" ;)

solved with https://github.com/peterpeterparker/ionicv4-and-beyond/commit/fe03ec5e68fc2d2e5804d919e7ac3030cff6fdba

thx 👍
